spring.application.name=prog

# Conexión a TiDB Cloud MySQL
spring.datasource.url=jdbc:mysql://gateway01.us-east-1.prod.aws.tidbcloud.com:4000/centros_acopio?sslMode=REQUIRED&useSSL=true
spring.datasource.username=4ETssD6NQCxZQxX.root
spring.datasource.password=Hd08fVZ0XIsIKS1i
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
